name: Run All Tests

on: 
    push: 
        branches: 
            - main
    pull_request:
        branches:
            - main

jobs:
    build_site:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./mariebmo

        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '20.x'
                cache: 'npm'

            - name: Run Unit Tests
              run: npm run test:unit

            - name: Run Integration Tests
              run: npm run test:integration