name: Run All Tests

on: 
    push: 
        branches: 
            - main
            - develop
    pull_request:
        branches:
            - main

jobs:
    build_site:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./mariebmo

        steps:
            - uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: npm

            - name: Install Dependencies
              run: npm ci


            - name: Run Unit Tests
              run: npm run test:unit

            - name: Install Playwright Browsers
              run: npx playwright install --with-deps

            - name: Run Integration Tests
              run: npm run test:integration