name: Run All Tests

on: 
    push: 
        branches: 
            - main
            - develop
    pull_request:
        branches:
            - main

jobs:
    build_site:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./mariebmo

        steps:
            - uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: npm

            - name: Run Unit Tests
              run: npm ci && npm run test:unit

            - name: Run Integration Tests
              run: npm ci && npx playwright install && npm run test:integration